"""
This script is to generate image of veh-veh collision from visualization files (json format)
The input should be generated by ctrl-sim under json format
Parameters to set: path (path of input files (folder)), save_dir (path of output)
"""
import matplotlib.pyplot as plt 
import numpy as np 
import os 
import json
import math
from tqdm import tqdm 
from matplotlib.patches import FancyBboxPatch
from matplotlib.patches import Rectangle
from matplotlib.patches import Polygon
import matplotlib.patches as mpatches
import matplotlib.transforms as transforms


def radiens_to_degrees(radians):
    degrees = radians*(180/3.141592653589793)
    return degrees

def get_road_type_onehot(road_type):
    road_types = {"none": 0, "lane": 1, "road_line": 2, "road_edge": 3, "stop_sign": 4, "crosswalk": 5,
                      "speed_bump": 6, "other": 7}
    return np.eye(len(road_types))[road_types[road_type]]

def get_object_type_onehot(agent_type):
    agent_types = {"unset": 0, "vehicle": 1, "pedestrian": 2, "cyclist": 3, "other": 4}
    return np.eye(len(agent_types))[agent_types[agent_type]]


path = r"c:\Users\cwang76\AppData\Local\Google\Cloud SDK\viz_150920255"   # path of a folder (not a file)
save_dir = './scenario506'  # output folder 

max_num_roads_pts_per_polyline = 100
files = os.listdir(path)


for e, file in enumerate(files):
    with open(os.path.join(path, file), 'r') as f:
        data = json.load(f)
    imagename = file.split('.')[0]
    imagename = imagename.split('_', 1)[0]
    seed = file.split('_')[-1]
    seed = seed.split('.')[0]
    name = data['name']
    roads_data = data['roads']
    map_id = file.split('_')[3]
    num_roads = len(roads_data)
    # print(f"the number of roads is {num_roads}")
    final_roads = []
    final_road_types = []   # 0: none, 1: lane, 2: road_line, 3: road_edge, 4: stop_sign, 5: cross_walk, 6: speed_bump, 7: others
    for n in range(num_roads):
        curr_road_rawdat = roads_data[n]['geometry']
        
        # print(curr_road_rawdat)
        if isinstance(curr_road_rawdat, dict):
            # print(f"the type of curr_road_dat is {type(curr_road_rawdat)}")
            final_roads.append(np.array((curr_road_rawdat['x'], curr_road_rawdat['y'], 1.0)).reshape(1,-1).repeat(max_num_roads_pts_per_polyline, 0))
            final_road_types.append(get_road_type_onehot(roads_data[n]['type']))
        else:
            curr_road = []
            for p in range(len(curr_road_rawdat)):
                curr_road.append(np.array((curr_road_rawdat[p]['x'], curr_road_rawdat[p]['y'], 1.0)))
                if len(curr_road) == max_num_roads_pts_per_polyline:
                    final_roads.append(np.array(curr_road))
                    curr_road = []
                    final_road_types.append(get_road_type_onehot(roads_data[n]['type']))
            if len(curr_road) < max_num_roads_pts_per_polyline and len(curr_road) > 0 : 
                tmp_curr_road = np.zeros((max_num_roads_pts_per_polyline, 3))
                tmp_curr_road[:len(curr_road)] = np.array(curr_road)
                final_roads.append(tmp_curr_road)
                final_road_types.append(get_road_type_onehot(roads_data[n]['type']))
            

    final_roads = np.array(final_roads)
    final_road_types = np.array(final_road_types)

    agents_data = data['objects']
    num_agents = len(agents_data)
    agent_data = []
    agent_types = []
    agent_goals = []
    agent_rewards = []
    parked_agents_ids = [] # not plot the parked agent
    agent_ctrlsim = []   # agents controlled by ctrl-sim
    for n in range(len(agents_data)):
        ag_position  = agents_data[n]['position']
        x_values = [entry['x'] for entry in ag_position]
        y_values = [entry['y'] for entry in ag_position]
        ag_position = np.column_stack((x_values, y_values))
        ag_heading = np.array(agents_data[n]['heading']).reshape(-1,1)
        ag_velocity = agents_data[n]['velocity']
        x_values = [entry['x'] for entry in ag_velocity]
        y_values = [entry['y'] for entry in ag_velocity]
        ag_velocity = np.column_stack((x_values, y_values))
        if np.linalg.norm(ag_velocity, axis= -1).mean() < 0.05:
            parked_agents_ids.append(n)
        ag_existence = np.array(agents_data[n]['existence']).reshape((-1,1))
        
        ag_length = np.ones((len(ag_position),1)) * agents_data[n]['length']
        ag_width = np.ones((len(ag_position), 1)) * agents_data[n]['width']
        agent_type = get_object_type_onehot(agents_data[n]['type'])

        rewards = np.array(agents_data[n]['reward']) * ag_existence

        goal_position_x = agents_data[n]['goal_position']['x']
        goal_position_y = agents_data[n]['goal_position']['y']
        goal_position = np.repeat(np.array([goal_position_x, goal_position_y])[None, :], len(ag_position), 0)

        if agents_data[n]['is_ctrl_sim']:
            agent_ctrlsim.append(n)

        ag_state = np.concatenate((ag_position, ag_velocity, ag_heading, ag_length, ag_width, ag_existence), axis=-1)
        agent_data.append(ag_state)
        agent_types.append(agent_type)
        agent_goals.append(goal_position)
        agent_rewards.append(rewards)
    # shape of agent_data is [num_agents, num_timestep, 8 (num of metrics (position 2, velocity 2, heading 1, ag_length 1, ag_width 1, ag_existence 1))]
    agent_data = np.array(agent_data)
    agent_types = np.array(agent_types)
    agent_goals = np.array(agent_goals)
    agent_rewards = np.array(agent_rewards)
    parked_agents_ids = np.array(parked_agents_ids)
    final_road_points = final_roads
    agent_states = agent_data
    goals = agent_goals

    agent_color = 'pink'
    focal_color = 'lightseagreen'
    agent_alpha = 0.25
    focal_alpha = 1.0

    
    for i in range(len(agent_ctrlsim)):
        scene_id = i
        other_agent_idx = -1
        focal_agent_idx = agent_ctrlsim[i]
        focal_idx_veh_veh_rewards = agent_rewards[focal_agent_idx, :, 6]
        focal_idx_veh_edge_rewards = agent_rewards[focal_agent_idx, :, 7]
        other_idx_veh_vhe_rewards = agent_rewards[other_agent_idx, :, 6]
        other_idx_veh_edge_rewards = agent_rewards[other_agent_idx, :, 7]
        found_collision = False
        # for ts in range(90):
        #     if focal_idx_veh_vhe_rewards[ts] == 1 and other_idx_veh_vhe_rewards[ts] == 1: 
        #         first_collision_timestep = ts
        #         found_collision = True
        #         break
        # if not found_collision:
        #     first_collision_timestep = int(np.sum(agent_data[focal_agent_idx, :, -1]) - 1)
        
        if np.sum(focal_idx_veh_veh_rewards) == 0:
            print(f"Scene {i} has no veh-veh collision, pass to next scene")
            continue

        first_collision_timestep = np.where(focal_idx_veh_veh_rewards == 1)[0][0]
        collision_idxs = list(np.where(agent_rewards[:, first_collision_timestep, 6] == 1)[0])
        collision_idxs.remove(focal_agent_idx)
        # if len(collision_idxs) > 1:
        #     continue
        other_agent_idx = collision_idxs[0]
        # print(f'the other agent idx is {other_agent_idx}')

        intermediate_timesteps = [first_collision_timestep]

        cur_timestep = first_collision_timestep -10
        while cur_timestep > 5:
            intermediate_timesteps.append(cur_timestep)
            cur_timestep -= 10
        
        num_intermediate_timesteps = len(intermediate_timesteps)
        intermediate_alphas = list((np.arange(num_intermediate_timesteps - 1) / (num_intermediate_timesteps - 1)) * 0.75 + 0.25)
        intermediate_alphas.append(1.0)
        intermediate_timesteps = intermediate_timesteps[::-1]

        intermediate_alphas.insert(0, 0.25)
        intermediate_timesteps.insert(0, 0)

        for r in range(len(final_road_points)):
            if final_road_types[r, 3] != 1:  # if the type is not road_edge, jump to next iteration
                continue                    
            mask = final_road_points[r, :, 2].astype(bool)
            plt.plot(final_road_points[r, :, 0][mask], final_road_points[r, :, 1][mask], color = 'gray', linewidth = 0.5)   # plot road_edge
            
        for r in range(len(final_road_points)):
            if final_road_types[r, 2] != 1:   # if the type is not road_line, jump to next iteration
                continue
            mask = final_road_points[r, :, 2].astype(bool)
            plt.plot(final_road_points[r, :, 0][mask], final_road_points[r, :, 1][mask], color='lightgray', linewidth = 0.3)   # plot road_line 

        coordinates = agent_states[:, :, :2]
        coordinates_mask = agent_states[:, :, -1].astype(bool).copy()
        
        coordinates_mask[:, first_collision_timestep:] = False
        unmodified_coordinates_mask = agent_states[:, :, -1].astype(bool)

        for a in range(len(coordinates)):
            if a == focal_agent_idx:
                x_min = np.min(coordinates[a, :, 0][unmodified_coordinates_mask[a]]) - 50
                x_max = np.max(coordinates[a, :, 0][unmodified_coordinates_mask[a]]) + 50
                y_min = np.min(coordinates[a, :, 1][unmodified_coordinates_mask[a]]) - 50
                y_max = np.max(coordinates[a, :, 1][unmodified_coordinates_mask[a]]) + 50

                if (x_max - x_min) > (y_max - y_min):
                    diff = (x_max - x_min) - (y_max - y_min)
                    diff_side = diff / 2
                    y_min -= diff_side
                    y_max += diff_side
                else:
                    diff = (y_max - y_min) - (x_max - x_min)
                    diff_side = diff / 2
                    x_min -= diff_side
                    x_max += diff_side

        for a in range(len(coordinates)):
            if a == focal_agent_idx:
                color = focal_color
                alpha = focal_alpha
                zord = 3
                zord_evolve = 5
            elif a == other_agent_idx:
                color = agent_color
                alpha = focal_alpha
                zord = 2
                zord_evolve = 4
            else: 
                color = 'bisque'
                alpha = agent_alpha
                zord = 2
                zord_evolve = 4
            if a == focal_agent_idx or a == other_agent_idx:
                plt.plot(coordinates[a, :, 0][coordinates_mask[a]], coordinates[a, :, 1][coordinates_mask[a]], color=color, linewidth=0.75, zorder = zord, alpha=alpha)
            else:
                length = agent_states[a, first_collision_timestep, 5]
                width = agent_states[a, first_collision_timestep, 6]
                bbox_x_min = coordinates[a, first_collision_timestep, 0] - width / 2
                bbox_y_min = coordinates[a, first_collision_timestep, 1] - length / 2
                lw = (0.35) / ((x_max - x_min) / 140)
                rectangle = mpatches.FancyBboxPatch((bbox_x_min, bbox_y_min), width, length, ec='black', fc=color, linewidth=lw, alpha=0.25, 
                                                    boxstyle=mpatches.BoxStyle("Round", pad=0.3), zorder=4)
                t = transforms.Affine2D().rotate_deg_around(coordinates[a, first_collision_timestep, 0], coordinates[a, first_collision_timestep, 1], radiens_to_degrees(agent_states[a, first_collision_timestep, 4]) - 90) + plt.gca().transData

                rectangle.set_transform(t)

                plt.gca().set_aspect('equal', adjustable='box')
                plt.gca().add_patch(rectangle)

                heading_length = length / 2 + 1.5
                heading_angle_red = agent_states[a, first_collision_timestep, 4]
                vehicle_center = coordinates[a, first_collision_timestep, :2]

                line_end_x = vehicle_center[0] + heading_length * math.cos(heading_angle_red)
                line_end_y = vehicle_center[1] + heading_length * math.sin(heading_angle_red)
                # draw the headline
                plt.plot([vehicle_center[0], line_end_x], [vehicle_center[1], line_end_y], color='black', zorder=6, alpha=0.25, linewidth=0.25/((x_max-x_min)/140))

            if a == focal_agent_idx or a == other_agent_idx:
                for j in range(len(intermediate_timesteps)):
                    if j == len(intermediate_timesteps) - 1:
                        if intermediate_timesteps[j] == int(np.sum(agent_data[focal_agent_idx, :, -1]) - 1):
                            ec = 'green'
                        else:
                            ec = 'red'
                        lw = (0.5) / ((x_max - x_min) / 140)
                    else:
                        ec = 'black'
                        lw = (0.35) / ((x_max - x_min) / 140)
                    
                    length = agent_states[a, intermediate_timesteps[j], 5]
                    width = agent_states[a, intermediate_timesteps[j], 6]
                    bbox_x_min = coordinates[a, intermediate_timesteps[j], 0] - width / 2
                    bbox_y_min = coordinates[a, intermediate_timesteps[j], 1] - length / 2

                    rectangle = mpatches.FancyBboxPatch((bbox_x_min, bbox_y_min), width, length, ec=ec, fc=color, linewidth=lw, alpha=intermediate_alphas[j],
                                                        boxstyle=mpatches.BoxStyle("Round", pad=0.3), zorder=zord_evolve)
                    t = transforms.Affine2D().rotate_deg_around(coordinates[a, intermediate_timesteps[j], 0], coordinates[a, intermediate_timesteps[j], 1], radiens_to_degrees(agent_states[a, intermediate_timesteps[j], 4]) - 90) + plt.gca().transData

                    # Apply the transformation to rectangle
                    rectangle.set_transform(t)
                    
                    plt.gca().set_aspect('equal', adjustable='box')
                    plt.gca().add_patch(rectangle)

                    if j == len(intermediate_timesteps) - 1:
                        heading_length = length / 2 + 1.5
                        heading_angle_red = agent_states[a, first_collision_timestep, 4]
                        vehicle_center = coordinates[a, first_collision_timestep, :2]
                        
                        line_end_x = vehicle_center[0] + heading_length * math.cos(heading_angle_red)
                        line_end_y = vehicle_center[1] + heading_length * math.sin(heading_angle_red)

                        plt.plot([vehicle_center[0], line_end_x], [vehicle_center[1], line_end_y], color='black', zorder=6, alpha=1.0, linewidth=0.25 / ((x_max-x_min)/140))
                # add the id for each agent 
            cx, cy = coordinates[a, first_collision_timestep, :2]
            plt.text(cx, cy, str(a), fontsize=6, zorder=6, alpha=0.8)

        plt.xlim(x_min, x_max)
        plt.ylim(y_min, y_max)

        plt.tick_params(left=False, right=False, labelleft=False, labelbottom=False, bottom=False)

        for a in range(len(goals)):
            if a == focal_agent_idx:
                color = focal_color
                ec = 'teal'
            elif a == other_agent_idx:
                color = agent_color
                ec = 'violet'
            else:
                continue
            
            lw = 1/((x_max-x_min) / 70)
            plt.scatter(goals[a, 0, 0], goals[a, 0, 1], color=color, s=int(35/((x_max-x_min)/70)), zorder=10, edgecolors='black', linewidth=lw)

        
        os.makedirs(save_dir, exist_ok=True)

        image_name = os.path.join(save_dir, f"{e}_seed{seed}_{scene_id}.png")
        print(f"saving the image {image_name} in {save_dir}")
        plt.tight_layout()
        plt.savefig(image_name, dpi=500)
        plt.clf()